image: debian:sid

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  before_script:
    - apt update && apt -y install cmake g++ ninja-build libglew-dev libglfw3-dev
  script:
    - mkdir build && cd build
    - cmake -G Ninja ..
    - ninja
    - ninja install
    - ctest -V
